apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gogs
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gogs
    spec:
      containers:
      - image: docker.io/gogs/gogs
        name: gogs
        env:
        - name: GOGS_HOST
          value: "db pod name"
        - name: GOGS_USER
          value: postgres
        - name: GOGS_DB_NAME
          value: "db name"
        - name: GOGS_PASSWORD
          value: "db password"
        resources: {}
status: {}
